@startuml
!pragma layout smetana

object Quiz
object Question
object Answer
object Score
object UserResponse
object Category
object User

' Komposition - domain.Quiz består af Questions
Quiz *-- Question

' Komposition - domain.Question består af Answers
Question *-- Answer

' Association - domain.Quiz tracker Score
Quiz -- Score

' Association - domain.Question tilhører Category
Question -- Category

' Association - domain.Question modtager UserResponse
Question -- UserResponse

' Dependency - DatabaseManager håndterer data
User ..> Quiz
User ..> Question
User ..> Answer

@enduml
